version: 2.1

commands:
  init-dependencies:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  unit-tests:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/node:<< parameters.version >>
    steps:
      - checkout
      - init-dependencies
      - run:
          name: Run tests
          command: |
            yarn test:unit:ci
            yarn lint:ci
      # Upload results
      - store_test_results:
          path: reports
      - store_artifacts:
          path: ./reports/mocha/test-results.xml
      - store_artifacts:
          path: ./reports/eslint/eslint.xml
  coverage:
    parameters:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - init-dependencies
      - run:
          name: Runs tests with coverage
          command: |
            yarn --version
            yarn coverage
      - run:
          name: Report test results to codecov
          command: yarn codecov
      - store_artifacts:
          path: ./coverage
      # - store_artifacts:
      #     path: ./.nyc_output

workflows:
  build:
    jobs:
      - unit-tests:
          version: '12'
      - coverage
